version: '2'

services:

  py38:
    image: ${PYTHON_IMAGE_NAME}:${PYTHON_IMAGE_VERSION}
    hostname: py38
    container_name: py38
    stdin_open: true
    volumes:
      - type: bind
        source: ./code
        target: /code
        read_only: false
      - type: bind
        source: ./result
        target: /result
        read_only: false

    # tty: true

  # py38:
  #   hostname: py38
  #   container_name: py38
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   stdin_open: true
  #   tty: true
