version: '2'

services:

    py38:
        image: ${PYTHON_IMAGE_NAME}:${PYTHON_IMAGE_VERSION}
        hostname: py38
        container_name: py38
        stdin_open: true
        volumes:
            - type: bind
              source: ../code
              target: /code
              read_only: false

    redis:
        image: redis:7.0.5
        hostname: redis
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - type: bind
              source: ../data/redis
              target: /data
              read_only: false
        environment:
            - REDIS_PORT=6379
    # tty: true

  # py38:
  #   hostname: py38
  #   container_name: py38
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   stdin_open: true
  #   tty: true
